### ISSUE TITLE
Increments for half move clock and full move number are inverted

### ISSUE THREAD

**Issue by milan-tom** [schnitzi/chessmovegen#1]
I was using your test data for a chess engine that I am building. Firstly, I would like to thank you for sharing this tool. It helped me to find some hard to reach bugs in my move generation code. There was one issue that I noticed though. The increment logic for the half move clock and move numbers in the fens seem to be inverted. For example, in [famous.json](https://github.com/schnitzi/chessmovegen/blob/bdc82470d8112b4b5b43ec79aa83c599fa1b0f20/src/main/resources/testcases/famous.json#L11), all of the full move numbers are incremented from 18 to 19 (they should only be incremented when it's white's turn to move) and some of the half move numbers remain at 4 (this is impossible as this must either reset to 0 or increment by 1 with each half move). I confirmed with online chess tools that this was an error, so please look into this when you get some time.

**Comment by schnitzi** [comment]
Ha, I didn't even think anyone would be using this, as I haven't promoted it yet (I think the test data is correct, but I still have a subtle perft failure on the move generator it uses to generate the data).  And it's also a nice coincidence, as I literally just pulled this project onto my new laptop like two hours ago to work on it during the holiday.  So I'll have a look at this issue tomorrow, and will reply here again if I get a fix in!

**Comment by schnitzi** [comment]
I believe these issues to be fixed now.  Please have a look and let me know what you think.  Thanks for the feedback!

**Comment by milan-tom** [comment]
Yes, it looks like the issues are fixed now. In the end, I chose to use the Stockfish `perft` function to generate my own test data, but this was a useful starting point nonetheless.
