### ISSUE TITLE
Inconsistent use of 'x' for captures

### ISSUE THREAD

**Issue by jlherren** [schnitzi/chessmovegen#2]
The 'x' is missing for some capture moves. For example it is not used here: https://github.com/schnitzi/chessmovegen/blob/master/src/main/resources/testcases/castling.json#L23 (There is a black rook on a2)

**Comment by schnitzi** [comment]
Hi Jean-Luc -- Sorry for the delay.  I believe this to be fixed now.  Check
it out and see if it matches your results.  Thanks for the correction!
Best regards, Mark

**Comment by jlherren** [comment]
That's perfect, thank you! The usage of 'x' is now consistent with my engine. If you don't mind I'll follow up with another bug :)

**Comment by schnitzi** [comment]
Please do!  I never mind fixing bugs.
