### ISSUE TITLE
taxing.json is missing checkmate annotation

### ISSUE THREAD

**Issue by jlherren** [schnitzi/chessmovegen#3]
In `taxing.json`, on the very first test case, 7 of the moves are annotated with + when they really should be annotated with #. (I don't know Kotlin, otherwise I would poke around the code myself)

```diff
diff --git a/src/main/resources/testcases/taxing.json b/src/main/resources/testcases/taxing.json
index 9e91af3..474d247 100644
--- a/src/main/resources/testcases/taxing.json
+++ b/src/main/resources/testcases/taxing.json
@@ -36,7 +36,7 @@
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/Q4Q2/pp1QN3/kB1N1KB1 b - - 1 1"
         },
         {
-          "move": "Nb3+",
+          "move": "Nb3#",
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/QN3Q2/pp1Q4/kB1N1KB1 b - - 1 1"
         },
         {
@@ -104,7 +104,7 @@
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/Q4Q2/ppQ5/kBNN1KB1 b - - 1 1"
         },
         {
-          "move": "Qdxb2+",
+          "move": "Qdxb2#",
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/Q4Q2/pQ6/kBNN1KB1 b - - 0 1"
         },
         {
@@ -168,11 +168,11 @@
           "fen": "R6R/3Q4/1Q4QQ/4Q3/2Q4Q/Q4Q2/pp6/kBNN1KB1 b - - 1 1"
         },
         {
-          "move": "Qaxa2+",
+          "move": "Qaxa2#",
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/5Q2/Qp1Q4/kBNN1KB1 b - - 0 1"
         },
         {
-          "move": "Qaxb2+",
+          "move": "Qaxb2#",
           "fen": "R6R/3Q4/1Q4Q1/4Q3/2Q4Q/5Q2/pQ1Q4/kBNN1KB1 b - - 0 1"
         },
         {
@@ -316,7 +316,7 @@
           "fen": "R6R/3Q4/1Q4Q1/4Q3/7Q/QQ3Q2/pp1Q4/kBNN1KB1 b - - 1 1"
         },
         {
-          "move": "Qcxa2+",
+          "move": "Qcxa2#",
           "fen": "R6R/3Q4/1Q4Q1/4Q3/7Q/Q4Q2/Qp1Q4/kBNN1KB1 b - - 0 1"
         },
         {
@@ -476,7 +476,7 @@
           "fen": "R6R/3Q4/1Q4Q1/8/2Q4Q/Q1Q2Q2/pp1Q4/kBNN1KB1 b - - 1 1"
         },
         {
-          "move": "Qexb2+",
+          "move": "Qexb2#",
           "fen": "R6R/3Q4/1Q4Q1/8/2Q4Q/Q4Q2/pQ1Q4/kBNN1KB1 b - - 0 1"
         },
         {
@@ -584,7 +584,7 @@
           "fen": "R6R/3Q4/6Q1/4Q3/2Q4Q/QQ3Q2/pp1Q4/kBNN1KB1 b - - 1 1"
         },
         {
-          "move": "Qbxb2+",
+          "move": "Qbxb2#",
           "fen": "R6R/3Q4/6Q1/4Q3/2Q4Q/Q4Q2/pQ1Q4/kBNN1KB1 b - - 0 1"
         },
         {
```

**Comment by schnitzi** [comment]
Well spotted.  I did have this TODO in the code:

`TODO decide: are checks, mates, and stalemates out of scope?`

though checks are covered now.  I think stalemates should be added as well -- if I'm suggesting the test data can be used to test notation, then it only makes sense.  AFAIK there's no notation for a move resulting in stalemate, is there?  I often see things like "1/2 - 1/2" but I don't think that's official.

**Comment by jlherren** [comment]
I have used Qb6@ to indicate all types of draws. But now that I search for it, it seems that I must have made that up. No SAN specification that I have found mentions any notation for draws and neither do sites like lichess.org or chess.com. The notation "1/2 - 1/2" comes from the PGN spec and seems unsuitable to be added to a SAN move. I think it's not necessary to include stalemate (or any draw) in the move itself, but that information could be included in the JSON, such as `{"move": "Qb6", "outcome": "stalemate", "fen": "..."}` or any other form. Users can then chose to do whatever with that information.

**Comment by schnitzi** [comment]
Hi Jean-Luc -- I believe I have it generating the correct notation now when
a move results in mate.  Please have a look and let me know what you
think.

I think it maybe needs another data file that's just about checkmates, or
maybe just about taxing move notation, but I want to make sure this is
working right first.

By the way if you've been testing your move generator with your own data
set, please feel free to suggest some FENs to include in the project!

Thanks as ever for the input...

Best regards
Mark

**Comment by jlherren** [comment]
Looks good, thanks!

I don't really have a dataset that I test with, other than this one and a few regression tests from previous bugs. The most significant test that I did was to download many GBs of [Lichess DB](https://database.lichess.org/) files for standard chess and chess 960. I then validate that my move generator agrees with the moves being played and that check and checkmate annotations match. My idea is that in those millions of games, there must be a few that would trigger potential bugs. Funny enough, this lead to the discovery of bugs in the Lichess DB.
